import React from 'react';
import {AbsoluteFill, Audio, Easing, Img, interpolate, Sequence, spring, staticFile, useCurrentFrame} from 'remotion';

const C={paper:'#f5f3ee',ink:'#171816',orange:'#ff7c00',muted:'#777b77',line:'#d9d8d0',dark:'#101112',panel:'#17191b',steel:'#303438'};
const mono='IBM Plex Mono, monospace';
const ease=Easing.bezier(.22,1,.36,1);
const lerp=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
const pop=(f:number,delay=0)=>spring({frame:f-delay,fps:30,config:{damping:22,stiffness:150,mass:.9}});
const items=[
 {name:'sword_knight_gold',short:'sword',color:'#df9d26',path:'M32 8l4 4L16 32l-2-2L32 8zm4-4L24 16l-4-4L32 0l4 4zM12 30l-4 4-2-2 4-4 2 2zm-4 4l-4 4H0v-4l4-4 4 4z'},
 {name:'potion_mana_elixir',short:'potion',color:'#5183c9',path:'M16 4h8v4h-8V4zm-4 8h16v6l-4 12H16L12 18v-6zm8 4a4 4 0 11-4 4 4 4 0 014-4z'},
 {name:'key_dungeon_rusty',short:'key',color:'#c98938',path:'M24 8a8 8 0 100 16 8 8 0 000-16zm0 12a4 4 0 110-8 4 4 0 010 8zM16 14H0v6h4v4h4v-4h4v4h4v-10z'},
 {name:'shield_valkyrie_steel',short:'shield',color:'#8094a4',path:'M4 4h32v12c0 10-8 18-16 22C12 34 4 26 4 16V4zm16 6v22c6-3 12-10 12-16V8H20z'},
 {name:'crown_royal_ruby',short:'crown',color:'#d76157',path:'M0 8l6 14 10-10 10 10 10-10 6 14H0V8zm8 20h24v4H8v-4z'},
 {name:'gem_flawless_emerald',short:'gem',color:'#548f73',path:'M20 0L40 16 20 40 0 16 20 0zm0 6L6 17l14 17 14-17L20 6z'},
];

const Asset=({index,size=120}:{index:number,size?:number})=><svg width={size} height={size} viewBox="-4 -4 50 50" style={{display:'block'}}><path d={items[index].path} fill={items[index].color}/></svg>;
const Arrow=({size=30,color='currentColor'}:{size?:number,color?:string})=><svg width={size} height={size} viewBox="0 0 32 32" fill="none"><path d="M5 16h21M18 7l9 9-9 9" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const Check=({size=24,color=C.orange}:{size?:number,color?:string})=><svg width={size} height={size} viewBox="0 0 24 24" fill="none"><path d="m5 12 4 4L19 6" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const Cursor=({x,y,click=false}:{x:number,y:number,click?:boolean})=><div style={{position:'absolute',left:x,top:y,zIndex:10}}>{click&&<div style={{position:'absolute',width:56,height:56,left:-21,top:-21,border:`2px solid ${C.orange}`,borderRadius:'50%',opacity:.55}}/>}<svg width="38" height="46" viewBox="0 0 38 46"><path d="M3 2 4 35 13 27 20 42 27 38 20 24 33 23Z" fill="white" stroke="#151515" strokeWidth="2"/></svg></div>;
const Logo=({size=50,dark=false}:{size?:number,dark?:boolean})=><div style={{width:size*1.8,height:size,overflow:'hidden',position:'relative',flexShrink:0,mixBlendMode:dark?'screen':'multiply'}}><Img src={staticFile('openassets-logo.png')} style={{position:'absolute',width:size*2.42,maxWidth:'none',left:-size*.385,top:-size*.325,filter:dark?'invert(1)':undefined}}/></div>;
const Brand=({dark=false}:{dark?:boolean})=><div style={{display:'flex',alignItems:'center',gap:18,color:dark?'#f5f3ee':C.ink}}><Logo size={33} dark={dark}/><span style={{fontSize:25,fontWeight:700,letterSpacing:-1}}>OpenAssets</span></div>;
const Kicker=({children,dark=false}:{children:React.ReactNode,dark?:boolean})=><div style={{fontFamily:mono,fontSize:18,letterSpacing:3,textTransform:'uppercase',color:dark?'#969c98':C.muted,display:'flex',alignItems:'center',gap:14}}><span style={{width:8,height:8,background:C.orange}}/>{children}</div>;
const Title=({children,frame,delay=0,style={}}:{children:React.ReactNode,frame:number,delay?:number,style?:React.CSSProperties})=><div style={{fontWeight:700,fontSize:88,lineHeight:1.02,letterSpacing:-5,opacity:lerp(frame,delay,delay+20),transform:`translateY(${lerp(frame,delay,delay+26,35,0)}px)`,...style}}>{children}</div>;
const checker={backgroundColor:'#eff0ec',backgroundImage:'linear-gradient(45deg,#e3e5df 25%,transparent 25%),linear-gradient(-45deg,#e3e5df 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#e3e5df 75%),linear-gradient(-45deg,transparent 75%,#e3e5df 75%)',backgroundSize:'24px 24px',backgroundPosition:'0 0,0 12px,12px -12px,-12px 0'};

const Frame=({children,dark=false,section=''}:{children:React.ReactNode,dark?:boolean,section?:string})=><AbsoluteFill style={{background:dark?C.dark:C.paper,color:dark?C.paper:C.ink,fontFamily:'Inter, sans-serif'}}><div style={{position:'absolute',left:84,right:84,top:48,display:'flex',justifyContent:'space-between',alignItems:'center'}}><Brand dark={dark}/><span style={{fontFamily:mono,fontSize:16,letterSpacing:1,color:dark?'#737a78':'#92968e'}}>ASSETS, UNPACKED.</span></div>{children}<div style={{position:'absolute',bottom:37,left:84,right:84,display:'flex',justifyContent:'space-between',fontFamily:mono,fontSize:15,color:dark?'#77807a':'#82867e',letterSpacing:1.5}}><span>{section}</span><span>OPEN SOURCE / BUILT FOR CREATORS</span></div></AbsoluteFill>;

const Sheet=({width=600,boxes=false,frame=0,scan=false}:{width?:number,boxes?:boolean,frame?:number,scan?:boolean})=>{const cell=width/3;return <div style={{width,height:cell*2,position:'relative',border:'1px solid #d7d9d0',background:'#fafbf7',overflow:'hidden'}}>{items.map((item,i)=>{const b=pop(frame,12+i*9);return <div key={item.short} style={{position:'absolute',left:(i%3)*cell,top:Math.floor(i/3)*cell,width:cell,height:cell,display:'flex',alignItems:'center',justifyContent:'center'}}><Asset index={i} size={cell*.59}/>{boxes&&<div style={{position:'absolute',inset:cell*.15,border:`2px solid ${C.orange}`,opacity:b}}><span style={{position:'absolute',top:-22,left:-2,background:C.orange,color:'#111',fontFamily:mono,fontSize:13,padding:'3px 5px'}}>0{i+1}</span>{[0,1,2,3].map(j=><i key={j} style={{position:'absolute',width:7,height:7,background:C.orange,top:j<2?-4:undefined,bottom:j>1?-4:undefined,left:j%2===0?-4:undefined,right:j%2===1?-4:undefined}}/>)}</div>}</div>})}{scan&&frame<95&&<div style={{position:'absolute',left:0,right:0,height:2,top:lerp(frame,0,85,0,cell*2),background:C.orange,boxShadow:'0 -18px 48px 12px #ff7c0020'}}/>}</div>};
const Window=({children,width=1350,height=680,title='OpenAssets / Workspace',style={}}:{children:React.ReactNode,width?:number,height?:number,title?:string,style?:React.CSSProperties})=><div style={{width,height,background:C.dark,border:'1px solid #383c3f',borderRadius:13,boxShadow:'0 28px 70px #11111118',overflow:'hidden',position:'relative',...style}}><div style={{height:49,background:'#202326',borderBottom:'1px solid #35393c',display:'flex',alignItems:'center',padding:'0 20px',gap:8}}>{['#797e80','#666c6f','#555c60'].map(c=><span key={c} style={{width:10,height:10,borderRadius:'50%',background:c}}/>)}<span style={{fontFamily:mono,fontSize:14,color:'#a7aba9',marginLeft:32}}>{title}</span><span style={{marginLeft:'auto',fontFamily:mono,fontSize:12,color:'#7e8780'}}>ANIMATED WORKFLOW DEMO</span></div>{children}</div>;

function Hook(){const f=useCurrentFrame();const split=lerp(f,67,112);return <Frame section="01 / ONE IMAGE, MANY ASSETS"><div style={{position:'absolute',left:92,top:233}}><Kicker>AI-powered asset extraction</Kicker><Title frame={f} delay={3} style={{marginTop:26,fontSize:105}}>One image.<br/><span style={{color:C.orange}}>Every asset.</span></Title><div style={{fontSize:28,lineHeight:1.5,color:C.muted,marginTop:31,opacity:lerp(f,25,50)}}>Turn packed artwork into<br/>individual, usable files.</div><div style={{marginTop:48,display:'flex',alignItems:'center',gap:20,opacity:lerp(f,40,65)}}><div style={{height:43,width:43,background:C.ink,color:C.paper,display:'flex',justifyContent:'center',alignItems:'center'}}><Arrow size={24}/></div><span style={{fontFamily:mono,fontSize:17,letterSpacing:1}}>MEET OPENASSETS</span></div></div><div style={{position:'absolute',left:860,top:215,width:930,height:660,transform:`translateY(${lerp(f,0,35,50,0)}px)`,opacity:lerp(f,0,20)}}><div style={{position:'absolute',left:36,top:70,width:820,height:520,background:'#e7e7df',transform:'rotate(-5deg)',border:'1px solid #d4d6cc',opacity:1-split}}/>{items.map((it,i)=>{const x0=90+(i%3)*226,y0=100+Math.floor(i/3)*226;const x1=50+(i%3)*274,y1=40+Math.floor(i/3)*278;return <div key={it.short} style={{position:'absolute',left:x0+(x1-x0)*split,top:y0+(y1-y0)*split,width:218+36*split,height:218+36*split,background:split>.02?'#fcfcf9':'#fcfcf9',border:`1px solid ${split>.02?'#d8dbd0':'transparent'}`,borderRadius:8*split,display:'flex',alignItems:'center',justifyContent:'center',transform:`rotate(${(1-split)*-5}deg) scale(${pop(f,i*3)})`,boxShadow:split>.01?'0 12px 35px #181b1610':undefined}}><Asset index={i} size={130}/><div style={{position:'absolute',bottom:15,fontFamily:mono,fontSize:14,color:C.muted,opacity:split}}>{it.short}.png</div></div>})}<div style={{position:'absolute',left:72,top:623,fontFamily:mono,fontSize:17,color:C.muted,opacity:lerp(f,82,115)}}><span style={{color:C.orange}}>01</span> packed sheet <span style={{margin:'0 16px'}}>→</span><span style={{color:C.ink}}>06</span> independent assets</div></div></Frame>}

function Upload(){const f=useCurrentFrame();const enter=lerp(f,25,67);return <Frame section="02 / UPLOAD"><div style={{position:'absolute',top:165,left:92}}><Kicker>Start with what you have</Kicker><Title frame={f} style={{marginTop:19,fontSize:78}}>Drop it in.</Title></div><div style={{position:'absolute',left:620,top:174,opacity:lerp(f,2,20),transform:`translateY(${lerp(f,0,25,40,0)}px)`}}><Window width={1190} height={720} title="OpenAssets / Upload"><div style={{padding:'45px 65px'}}><div style={{fontFamily:mono,fontSize:25,fontWeight:600,color:'white',letterSpacing:1}}>INJECT ASSET TARGET</div><div style={{fontSize:17,color:'#8c9490',marginTop:12}}>Sprite sheets, icon packs, illustrations.</div><div style={{marginTop:32,border:`1px dashed ${f>55?C.orange:'#505755'}`,height:449,position:'relative',display:'flex',alignItems:'center',justifyContent:'center',background:'#1b1f1c'}}><div style={{opacity:1-enter,textAlign:'center'}}><div style={{fontSize:65,color:'#69736d'}}>↓</div><div style={{color:'#a9b2a9',fontSize:23}}>Drop an image to begin</div><div style={{fontFamily:mono,fontSize:13,color:'#68766b',marginTop:14}}>PNG · JPG · WEBP</div></div><div style={{position:'absolute',transform:`translate(${(1-enter)*-560}px, ${(1-enter)*210}px) rotate(${(1-enter)*-7}deg) scale(${.8+.2*enter})`,opacity:lerp(f,18,32)}}><Sheet width={420}/><div style={{display:'flex',justifyContent:'space-between',color:'#bec6bd',fontFamily:mono,fontSize:13,padding:'14px 0'}}><span>rpg_pack_v1.png</span><span>1 image</span></div></div><div style={{position:'absolute',bottom:20,right:22,display:'flex',gap:9,alignItems:'center',fontFamily:mono,fontSize:14,color:C.orange,opacity:lerp(f,70,92)}}><Check size={18}/> READY TO DETECT</div></div></div></Window><Cursor x={lerp(f,25,67,-280,623)} y={lerp(f,25,67,590,328)} click={f>=65&&f<78}/></div><div style={{position:'absolute',left:94,top:525,color:C.muted,fontSize:28,lineHeight:1.5,opacity:lerp(f,25,50)}}>A sprite sheet.<br/>An icon grid.<br/>A whole set of possibilities.</div><div style={{position:'absolute',left:94,top:823,width:320,height:2,background:C.line}}/></Frame>}

function Detect(){const f=useCurrentFrame();const edit=lerp(f,118,155);return <Frame dark section="03 / DETECT + FINE-TUNE"><div style={{position:'absolute',left:92,top:158,display:'flex',width:1736,justifyContent:'space-between',alignItems:'flex-end'}}><div><Kicker dark>Keep control of every crop</Kicker><Title frame={f} style={{marginTop:18,fontSize:73}}>Detected. <span style={{color:C.orange}}>Refined.</span></Title></div><div style={{fontSize:23,color:'#a0aaa1',paddingBottom:4,opacity:lerp(f,35,60)}}>Review the boxes. Adjust the edges.</div></div><div style={{position:'absolute',left:168,top:330,transform:`translateY(${lerp(f,0,27,45,0)}px)`,opacity:lerp(f,0,20)}}><Window width={1584} height={611} title="OpenAssets / Editor"><div style={{height:50,borderBottom:'1px solid #34383a',display:'flex',gap:24,alignItems:'center',padding:'0 25px',fontFamily:mono,fontSize:13,color:'#9ca69f'}}><span style={{color:C.orange}}>SELECT</span><span>MOVE</span><span>DRAW BOX</span><span style={{marginLeft:'auto'}}>rpg_pack_v1.png</span><span>100%</span></div><div style={{position:'absolute',left:0,top:99,bottom:0,width:315,borderRight:'1px solid #353a37',padding:24}}><div style={{fontFamily:mono,fontSize:14,color:'#b4bfb6',letterSpacing:1}}>DETECTIONS <span style={{color:C.orange,marginLeft:21}}>{Math.min(6,Math.max(0,Math.floor((f-18)/10)+1))}</span></div>{items.map((it,i)=><div key={it.short} style={{display:'flex',alignItems:'center',gap:18,borderBottom:'1px solid #292f2b',padding:'12px 0',opacity:lerp(f,18+i*10,28+i*10)}}><Asset index={i} size={37}/><span style={{fontFamily:mono,fontSize:14,color:i===0&&f>110?C.orange:'#a0aba3'}}>asset_00{i+1}</span><span style={{marginLeft:'auto'}}><Check size={14} color="#708977"/></span></div>)}<div style={{position:'absolute',left:24,right:24,bottom:23,padding:17,background:C.orange,textAlign:'center',fontFamily:mono,fontSize:14,fontWeight:700,color:'#121412'}}>EXPORT →</div></div><div style={{position:'absolute',left:424,top:123}}><Sheet width={630} boxes frame={f-8} scan/><div style={{position:'absolute',left:31-edit*10,top:30-edit*10,width:147+edit*20,height:147+edit*20,border:`2px solid ${C.orange}`,opacity:lerp(f,110,123)}}><span style={{position:'absolute',left:-5,top:-5,width:9,height:9,background:C.orange}}/></div></div><Cursor x={lerp(f,110,155,595,445)} y={lerp(f,110,155,222,141)} click={f>137&&f<151}/><div style={{position:'absolute',right:27,top:130,width:190,padding:21,border:'1px solid #333b34',fontFamily:mono,fontSize:13,lineHeight:2,color:'#9ba79d',opacity:lerp(f,110,132)}}><span style={{color:C.orange}}>BOUNDING BOX</span><br/>X {Math.round(lerp(f,118,155,31,21))} / Y {Math.round(lerp(f,118,155,30,20))}<br/>W {Math.round(lerp(f,118,155,147,167))}<br/>H {Math.round(lerp(f,118,155,147,167))}<div style={{marginTop:18,color:'#d4ddd3'}}>Your crop.<br/>Your call.</div></div></Window></div></Frame>}

function Name(){const f=useCurrentFrame();return <Frame section="04 / SMART AI EXPORT"><div style={{position:'absolute',left:92,top:158}}><Kicker>Names that mean something</Kicker><Title frame={f} style={{marginTop:20,fontSize:80}}>From <span style={{fontFamily:mono,fontWeight:400,fontSize:62}}>asset_001</span><br/>to <span style={{color:C.orange}}>sword_knight_gold.</span></Title></div><div style={{position:'absolute',left:112,top:446,display:'grid',gridTemplateColumns:'repeat(3, 544px)',gap:24}}>{items.map((it,i)=>{const reveal=lerp(f,43+i*13,62+i*13);return <div key={it.short} style={{height:214,border:'1px solid #d8dbd1',background:'#fcfcf8',display:'flex',alignItems:'center',padding:23,gap:24,opacity:pop(f,5+i*4),transform:`translateY(${(1-pop(f,5+i*4))*35}px)`}}><div style={{...checker,width:146,height:158,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,borderRadius:4}}><Asset index={i} size={106}/></div><div style={{flex:1,minWidth:0}}><div style={{fontFamily:mono,fontSize:13,color:C.muted,letterSpacing:1,marginBottom:16}}>0{i+1} / PNG</div><div style={{fontSize:19,fontWeight:600,color:C.ink,position:'relative',height:48,display:'flex',alignItems:'center'}}><span style={{opacity:1-reveal,position:'absolute'}}>asset_00{i+1}.png</span><span style={{opacity:reveal,overflowWrap:'anywhere'}}>{it.name}.png</span></div><div style={{fontFamily:mono,fontSize:13,color:'#748876',marginTop:15,opacity:reveal,display:'flex',gap:8,alignItems:'center'}}><Check size={17} color="#748876"/> NAMED + ISOLATED</div></div></div>})}</div><div style={{position:'absolute',top:282,right:107,width:338,fontSize:23,lineHeight:1.55,color:C.muted,opacity:lerp(f,40,63)}}>AI naming.<br/>Background removal.<br/><span style={{color:C.ink}}>Individual transparent PNGs.</span></div></Frame>}

function Export(){const f=useCurrentFrame();const z=lerp(f,67,113);return <Frame section="05 / EXPORT"><div style={{position:'absolute',left:92,top:188}}><Kicker>Your next build starts here</Kicker><Title frame={f} style={{marginTop:24,fontSize:91}}>Clean assets.<br/><span style={{color:C.orange}}>One ZIP.</span></Title><div style={{fontSize:27,color:C.muted,lineHeight:1.5,marginTop:32,opacity:lerp(f,22,47)}}>Select your assets.<br/>Export the pack.<br/>Put it to work.</div><div style={{display:'flex',alignItems:'center',gap:14,marginTop:40,fontFamily:mono,fontSize:18,color:C.ink,opacity:lerp(f,60,80)}}><Check/> OPTIONAL 2× AI UPSCALE</div></div><div style={{position:'absolute',left:800,top:184,width:990,height:720}}>{items.map((it,i)=>{const x=(i%3)*250+40,y=Math.floor(i/3)*225+45;return <div key={it.short} style={{position:'absolute',left:x+(330-x)*z,top:y+(260-y)*z,width:225,height:197,background:'#fafbf6',border:'1px solid #d4d9cd',display:'flex',alignItems:'center',justifyContent:'center',borderRadius:6,opacity:1-lerp(f,95,116),transform:`scale(${1-z*.55}) rotate(${z*(i-2.5)*10}deg)`,boxShadow:'0 8px 18px #2932230a'}}><Asset index={i} size={102}/><span style={{position:'absolute',top:15,right:15,width:23,height:23,display:'flex',alignItems:'center',justifyContent:'center',background:C.ink}}><Check size={15} color="white"/></span><span style={{position:'absolute',bottom:13,fontFamily:mono,fontSize:13,color:C.muted}}>{it.short}.png</span></div>})}<div style={{position:'absolute',left:234,top:112,width:454,height:450,background:C.ink,color:C.paper,borderRadius:16,boxShadow:'12px 16px 0 #ff7c00',transform:`scale(${.82+.18*pop(f,97)})`,opacity:lerp(f,99,120),display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',right:54,top:0,width:29,height:200,borderLeft:'1px solid #696c63',borderRight:'1px solid #696c63',background:'repeating-linear-gradient(to bottom, #e9e6da 0px, #e9e6da 7px, transparent 7px, transparent 16px)'}}/><div style={{fontFamily:mono,fontSize:83,letterSpacing:-6,marginTop:52}}>.zip</div><div style={{fontSize:25,fontWeight:500,marginTop:19}}>rpg_assets.zip</div><div style={{fontFamily:mono,fontSize:15,color:'#b8c1b4',marginTop:19}}>6 ASSETS / READY TO DOWNLOAD</div></div><div style={{position:'absolute',left:246,top:624,width:433,height:59,background:C.orange,color:C.ink,display:'flex',alignItems:'center',justifyContent:'center',gap:23,fontSize:20,fontWeight:600,opacity:lerp(f,123,145)}}>Download pack <span style={{fontSize:31}}>↓</span></div><Cursor x={lerp(f,125,162,800,570)} y={lerp(f,125,162,702,650)} click={f>165&&f<178}/></div></Frame>}

function Collection(){const f=useCurrentFrame();return <Frame dark section="06 / KEEP IT. SHARE IT."><div style={{position:'absolute',left:92,top:173}}><Kicker dark>Make it a library</Kicker><Title frame={f} style={{marginTop:23,fontSize:86}}>Good assets<br/>deserve<br/><span style={{color:C.orange}}>a home.</span></Title><div style={{fontSize:26,color:'#99a397',marginTop:36,lineHeight:1.5,opacity:lerp(f,22,42)}}>Organize a collection.<br/>Publish a shareable gallery.</div></div><div style={{position:'absolute',left:730,top:180,opacity:lerp(f,0,20),transform:`translateY(${lerp(f,0,27,30,0)}px)`}}><Window width={1085} height={638} title="OpenAssets / Collections"><div style={{padding:'31px 36px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:29,fontWeight:600,color:'white'}}>RPG essentials</div><div style={{fontFamily:mono,fontSize:13,color:'#839183',marginTop:12}}>6 ASSETS · 1 COLLECTION</div></div><span style={{padding:'10px 16px',fontFamily:mono,fontSize:12,color:C.orange,border:'1px solid #6a4520',opacity:lerp(f,30,55)}}>PUBLISHED ↗</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(3, 1fr)',gap:16,marginTop:27}}>{items.map((it,i)=><div key={it.short} style={{height:184,border:'1px solid #364033',background:'#1b211b',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:12,opacity:pop(f,6+i*5),transform:`translateY(${(1-pop(f,6+i*5))*20}px)`}}><Asset index={i} size={92}/><span style={{fontFamily:mono,fontSize:13,color:'#a9b6a5'}}>{it.short}.png</span></div>)}</div></div></Window></div><div style={{position:'absolute',left:747,top:862,width:1037,display:'flex',justifyContent:'space-between',opacity:lerp(f,45,68)}}>{['WEB APP','CHROME EXTENSION','REST API'].map((text,i)=><div key={text} style={{fontFamily:mono,fontSize:16,color:'#abb6a5',display:'flex',alignItems:'center',gap:13}}><div style={{width:6,height:6,background:i===0?C.orange:'#778770'}}/>{text}</div>)}</div></Frame>}

function End(){const f=useCurrentFrame();return <Frame section="OPENASSETS / START EXTRACTING"><div style={{position:'absolute',left:0,right:0,top:231,display:'flex',flexDirection:'column',alignItems:'center'}}><div style={{opacity:lerp(f,0,20),transform:`scale(${.9+.1*pop(f)})`}}><Logo size={89}/></div><Title frame={f} delay={9} style={{textAlign:'center',fontSize:105,marginTop:35}}>Less slicing.<br/><span style={{color:C.orange}}>More creating.</span></Title><div style={{fontSize:29,color:C.muted,marginTop:29,opacity:lerp(f,31,52)}}>OpenAssets. AI-powered asset extraction.</div><div style={{display:'flex',gap:22,alignItems:'center',marginTop:49,background:C.ink,color:C.paper,padding:'20px 32px',opacity:lerp(f,45,67),transform:`translateY(${lerp(f,45,70,18,0)}px)`}}><span style={{fontSize:24,fontWeight:500}}>Explore the open-source project</span><Arrow size={27}/></div><div style={{fontFamily:mono,fontSize:19,color:C.muted,marginTop:27,opacity:lerp(f,59,80)}}>github.com/anandxdj/open_assets</div></div>{items.map((it,i)=><div key={it.short} style={{position:'absolute',left:i%2===0?120+Math.floor(i/2)*50:1565+Math.floor(i/2)*30,top:236+Math.floor(i/2)*233,opacity:lerp(f,20+i*3,50+i*3)*.32,transform:`rotate(${(i%2?1:-1)*12}deg) translateY(${Math.sin((f+i*14)/40)*7}px)`}}><Asset index={i} size={115}/></div>)}</Frame>}

const scenes=[{from:0,duration:150,component:Hook},{from:150,duration:150,component:Upload},{from:300,duration:210,component:Detect},{from:510,duration:210,component:Name},{from:720,duration:210,component:Export},{from:930,duration:120,component:Collection},{from:1050,duration:150,component:End}];
const Wrap=({duration,children}:{duration:number,children:React.ReactNode})=>{const f=useCurrentFrame();return <AbsoluteFill style={{opacity:Math.min(lerp(f,0,9),lerp(f,duration-8,duration,1,0))}}>{children}</AbsoluteFill>};
export function OpenAssetsShowcase(){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper}}><Audio src={staticFile('soundtrack.wav')} volume={.85}/>{scenes.map(s=><Sequence key={s.from} from={s.from} durationInFrames={s.duration}><Wrap duration={s.duration}><s.component/></Wrap></Sequence>)}<div style={{position:'absolute',bottom:0,left:0,height:4,width:1920*(f/1199),background:C.orange}}/></AbsoluteFill>}
